import { calculateSeason, calculateBridge, suppliedWinter, money, round } from './calc.mjs';

const KEY = 'pork-garlic-year2-winter-planner-v1';
const clone = (v) => JSON.parse(JSON.stringify(v));
const y1Machines = [
  { id:'M1', modelId:'M1', name:'Machine 1', capacity:72000, purchaseCost:35000, maintenance:1800, depreciation:4375, life:8 },
  { id:'M2', modelId:'M2', name:'Machine 2', capacity:120000, purchaseCost:95000, maintenance:2900, depreciation:11875, life:8 },
  { id:'M3', modelId:'M3', name:'Machine 3', capacity:68000, purchaseCost:38000, maintenance:2100, depreciation:4750, life:8 },
  { id:'M4', modelId:'M4', name:'Machine 4', capacity:95000, purchaseCost:70000, maintenance:2900, depreciation:8750, life:8 },
  { id:'M5', modelId:'M5', name:'Machine 5', capacity:45000, purchaseCost:28000, maintenance:1300, depreciation:3500, life:8 },
  { id:'M6', modelId:'M6', name:'Machine 6', capacity:110000, purchaseCost:90000, maintenance:2900, depreciation:11250, life:8 }
];
const y1Premises = [
  {id:'A',name:'Premise A (P)',slots:1,rent:12000,transport:.3},{id:'B',name:'Premise B (P)',slots:1,rent:10000,transport:.4},
  {id:'C',name:'Premise C',slots:1,rent:12000,transport:.3},{id:'D',name:'Premise D',slots:1,rent:17000,transport:.1},
  {id:'E',name:'Premise E',slots:2,rent:15000,transport:.2},{id:'F',name:'Premise F (P)',slots:3,rent:16000,transport:.2}
];
const y1Params = { price:2, milkPrice:20000, milkYield:20000, salaries:10000, bonusRate:5, taxRate:10, premises:clone(y1Premises) };
const blankSeason = { production:0,milkTons:0,salesRequest:0,assumedSales:0,market:0,premise:'D',premises:['D'],machineUse:['M1'],purchases:[],borrowing:0,interestRate:0,repaymentTerm:0,principalRepayment:0,extraRepayment:0,minimumCosts:0 };
const y2Params = { price:2, milkPrice:20000, milkYield:20000, salaries:10000, bonusRate:5, taxRate:10,
  premises:clone(y1Premises), machines:clone(y1Machines)
};
const defaultScenario = { ...clone(blankSeason), production:60000,milkTons:3,salesRequest:60000,assumedSales:60000,market:3000,minimumCosts:0, purchases:[], sensitivitySales:45000 };
const defaults = () => ({ winter:{...clone(suppliedWinter),premises:['D']}, spring:clone(blankSeason),summer:clone(blankSeason),autumn:clone(blankSeason), year1Params:clone(y1Params),year1Machines:clone(y1Machines), y2Params:clone(y2Params), autumnOverride:{enabled:false,cash:0,debt:0,taxLoss:0,m1Life:0}, scenarioA:clone(defaultScenario),scenarioB:{...clone(defaultScenario),production:100000,milkTons:5,salesRequest:80000,assumedSales:80000,market:5000,sensitivitySales:60000}, recommendation:{choice:'A',reason:'Protect cash while Year 1 estimates are still being replaced.',assumption:'Actual Year 2 sales can be achieved without exceeding the planned allocation.'} });
let state;
try { state = JSON.parse(localStorage.getItem(KEY)) || defaults(); } catch { state = defaults(); }
// Update earlier saved browser states to the Year 1 rule catalog without discarding user edits.
const mergeCatalog = (current, rules) => rules.map(rule => ({ ...rule, ...(current || []).find(item => item.id === rule.id) }));
const mergePremiseRules = (current) => y1Premises.map(rule => {
  const saved = (current || []).find(item => item.id === rule.id);
  // Remove only the zero-value placeholders used by the first version; retain genuine later edits.
  const isLegacyPlaceholder = saved && (!saved.rent && !saved.transport) && (rule.id === 'E' || rule.id === 'F' || String(saved.name || '').includes('estimate'));
  return isLegacyPlaceholder ? { ...rule } : { ...rule, ...saved };
});
state.year1Machines = mergeCatalog(state.year1Machines, y1Machines);
state.year1Params = { ...y1Params, ...state.year1Params, premises: mergePremiseRules(state.year1Params?.premises), bonusRate:5, taxRate:10 };
state.y2Params = { ...y2Params, ...state.y2Params, premises: mergePremiseRules(state.y2Params?.premises), machines: mergeCatalog(state.y2Params?.machines, y1Machines) };
// Earlier versions listed Machine 2 as a zero-value placeholder. Replace that known placeholder with the Year 1 reference figures.
const oldM2 = state.y2Params.machines.find(machine => machine.id === 'M2');
if (oldM2 && !oldM2.capacity && !oldM2.purchaseCost && !oldM2.maintenance && !oldM2.depreciation) Object.assign(oldM2, y1Machines.find(machine => machine.id === 'M2'));
if (state.winter?.minimumCosts === 4204) state.winter.minimumCosts = 0;
if (state.scenarioA?.minimumCosts === 4204) state.scenarioA.minimumCosts = 0;
if (state.scenarioB?.minimumCosts === 4204) state.scenarioB.minimumCosts = 0;
state.uiSeason = ['winter','spring','summer','autumn'].includes(state.uiSeason) ? state.uiSeason : 'winter';

const $ = (s) => document.querySelector(s);
const title = (name, description) => `<div class="section-head"><div><h2>${name}</h2><p>${description}</p></div></div>`;
const nInput = (label,path,value,extra='') => `<label>${label}<input type="number" step="any" data-path="${path}" value="${value ?? 0}" ${extra}></label>`;
const tInput = (label,path,value) => `<label>${label}<input type="text" data-path="${path}" value="${String(value ?? '').replaceAll('"','&quot;')}"></label>`;
const select = (label,path,value,options) => `<label>${label}<select data-path="${path}">${options.map(([v,l])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${l}</option>`).join('')}</select></label>`;
const setPath = (path, val) => { const a=path.split('.'); let ref=state; a.slice(0,-1).forEach(k=>ref=ref[k]); ref[a.at(-1)]=val; };
const getPath = (path) => path.split('.').reduce((o,k)=>o?.[k], state);
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
const fmt = (n) => `Sh ${money(n)}`;
const inputValue = (el) => el.type === 'number' ? Number(el.value || 0) : el.value;

function seasonForm(key, season, result, isWinter=false) {
  const machineOptions = state.year1Machines;
  const inputMachineOptions = machineOptions;
  const premiseChecks = state.year1Params.premises.map(p => `<label><input type="checkbox" data-array="${key}.premises" value="${p.id}" ${season.premises?.includes(p.id)?'checked':''}> ${p.name}</label>`).join('');
  const machineChecks = inputMachineOptions.map(m=>`<label><input type="checkbox" data-array="${key}.machineUse" value="${m.id}" ${season.machineUse?.includes(m.id)||season.machineUse?.includes(m.sourceId)||season.machineUse?.includes(m.modelId)?'checked':''}> ${m.name} (${money(m.capacity)})</label>`).join('');
  const purchaseChecks = machineOptions.map(m=>`<label><input type="checkbox" data-array="${key}.purchases" value="${m.id}" ${season.purchases?.includes(m.id)?'checked':''}> Buy ${m.name}</label>`).join('');
  return `<article class="card"><h3>Year 1 ${key[0].toUpperCase()+key.slice(1)} ${isWinter?'<span class="chip">verification case</span>':'<span class="chip">estimate — replace later</span>'}</h3>${isWinter?'<p class="subtle">Supplied classroom test case. Bonus is 5% of positive gross profit; game tax is 10% after tax-loss use.</p>':'<p class="subtle">Planning estimate only. Do not treat this as a real classroom result. Choose any Year 1 rule premise or machine; a machine only contributes capacity when owned or purchased.</p>'}
  <div class="fields">${isWinter?nInput('Opening cash',`${key}.openingCash`,season.openingCash):''}${nInput('Planned production',`${key}.production`,season.production)}${nInput('Milk purchased (tons)',`${key}.milkTons`,season.milkTons)}${nInput('Sales request',`${key}.salesRequest`,season.salesRequest)}${nInput('Assumed actual sales',`${key}.assumedSales`,season.assumedSales)}${nInput('Market investment',`${key}.market`,season.market)}${nInput('Minimum costs',`${key}.minimumCosts`,season.minimumCosts)}${nInput('Borrowing',`${key}.borrowing`,season.borrowing)}${nInput('Interest rate (%)',`${key}.interestRate`,season.interestRate)}${nInput('Repayment term (seasons)',`${key}.repaymentTerm`,season.repaymentTerm)}${nInput('Principal repayment',`${key}.principalRepayment`,season.principalRepayment)}${nInput('Extra principal repayment',`${key}.extraRepayment`,season.extraRepayment)}</div>
  <div class="checks"><strong>Production premises (Year 1 game rules):</strong>${premiseChecks}</div><div class="checks"><strong>Machine use (Year 1 game rules):</strong>${machineChecks}</div><div class="checks"><strong>Machine purchases (Year 1 game rules):</strong>${purchaseChecks}</div>
  ${result ? resultBlock(result)+seasonDetails(result) : ''}</article>`;
}

function seasonDetails(r) { return `<details><summary>Show seasonal P&amp;L and cash flow</summary>${pnl(r)}<table class="table"><tbody><tr><td>Cash before finance</td><td>${fmt(r.cashBeforeFinance)}</td></tr><tr><td>Machine purchases (cash, not P&amp;L)</td><td>${fmt(-r.machinePurchases)}</td></tr><tr><td>Loan cash received / principal repayment</td><td>${fmt(r.borrowing)} / ${fmt(-r.principalRepayment)}</td></tr><tr><td>Closing debt / tax-loss pool</td><td>${fmt(r.debt)} / ${fmt(r.taxLoss)}</td></tr><tr><td>Unused milk / spoilage</td><td>${money(r.unusedMilk)} / ${money(r.spoilage)} units</td></tr></tbody></table></details>`; }

function resultBlock(r) { const flags=[]; if(r.flags.productionCapped)flags.push('<div class="warning">Production was capped by milk or active machine capacity.</div>'); if(r.flags.negativeBeforeFinance)flags.push('<div class="danger">Negative cash before finance / advance payments.</div>');if(r.flags.negativeClosing)flags.push('<div class="danger">Negative closing cash.</div>'); return `<div class="metric-grid"><div class="metric-box"><span>Net profit</span><div class="metric">${fmt(r.netProfit)}</div></div><div class="metric-box"><span>Closing cash</span><div class="metric">${fmt(r.closingCash)}</div></div><div class="metric-box"><span>Capacity / production</span><div class="metric">${money(r.activeCapacity)} <small>/ ${money(r.production)}</small></div></div></div>${flags.join('')}`; }

function renderWinterCheck(bridge) {
  const r=bridge.seasons[0].result, pass=r.netProfit===13621&&r.closingCash===82996;
  $('#winter-check').innerHTML=`${title('1. Year 1 Winter check','The supplied verification case is saved as the starting point.')}<div class="grid two"><div class="card"><h3>Expected result</h3><div class="metric-grid"><div class="metric-box"><span>Net profit</span><div class="metric">Sh 13,621</div></div><div class="metric-box"><span>Closing cash</span><div class="metric">Sh 82,996</div></div><div class="metric-box"><span>Machine 1 life</span><div class="metric">7 seasons</div></div></div><button data-action="restore-winter">Restore supplied Winter test case</button></div><div class="card">${pass?'<div class="success"><strong>PASS — supplied Winter check reconciles.</strong><br>Net profit and closing cash match the verification case.</div>':'<div class="warning"><strong>Check not passing.</strong><br>Restore the supplied case or review the edited inputs below.</div>'}<table class="table"><tbody><tr><td>Calculated net profit</td><td>${fmt(r.netProfit)}</td></tr><tr><td>Calculated closing cash</td><td>${fmt(r.closingCash)}</td></tr><tr><td>Posted minimum costs</td><td>${fmt(r.minimumCosts)}</td></tr></tbody></table></div></div>`;
}

function renderBridge(bridge) {
  const [winter,spring,summer,autumn]=bridge.seasons.map(x=>x.result);
  const seasonResults={winter,spring,summer,autumn};
  const labels={winter:'Winter',spring:'Spring',summer:'Summer',autumn:'Autumn'};
  const selected=state.uiSeason;
  $('#bridge').innerHTML=`${title('2. Finish Year 1 — planning bridge','Choose one season at a time. Spring, Summer and Autumn remain editable estimates until you enter real classroom results.')}<div class="season-nav card"><div><strong>Year 1 seasons</strong><p class="subtle">Cash, debt, tax losses and machine lives roll forward automatically.</p></div><div class="season-buttons">${Object.entries(labels).map(([key,label])=>`<button class="${key===selected?'selected':''}" data-season="${key}">${label}</button>`).join('')}</div></div>${seasonForm(selected,state[selected],seasonResults[selected],selected==='winter')}<div class="card"><h3>Year 1 position after Autumn</h3><div class="metric-grid"><div class="metric-box"><span>Annual profit</span><div class="metric">${fmt(bridge.annualProfit)}</div></div><div class="metric-box"><span>Autumn closing cash</span><div class="metric">${fmt(autumn.closingCash)}</div></div><div class="metric-box"><span>Debt / tax losses</span><div class="metric">${fmt(autumn.debt)} <small>/ ${fmt(autumn.taxLoss)}</small></div></div></div><p class="subtle">Owned machines at Autumn: ${autumn.machines.map(m=>`${m.name}: ${m.remainingLife} season(s)`).join(', ')||'none'}.</p></div><div class="card"><h3>Manual Autumn actual-results override</h3><p class="subtle">Use this only once you have official Year 1 Autumn results. It becomes the Year 2 Winter opening position and remains clearly labelled as a manual override.</p><div class="checks"><label><input type="checkbox" data-path="autumnOverride.enabled" ${state.autumnOverride.enabled?'checked':''}> Use manual actual-results override for Year 2</label></div><div class="fields">${nInput('Actual Autumn closing cash','autumnOverride.cash',state.autumnOverride.cash)}${nInput('Actual unpaid loans','autumnOverride.debt',state.autumnOverride.debt)}${nInput('Actual unused tax losses','autumnOverride.taxLoss',state.autumnOverride.taxLoss)}${nInput('Machine 1 remaining life','autumnOverride.m1Life',state.autumnOverride.m1Life)}</div></div>`;
}

function renderY2Settings() {
 const p=state.y2Params;
 const premRows=p.premises.map((x,i)=>`<tr><td>${tInput('',`y2Params.premises.${i}.name`,x.name)}</td><td>${nInput('',`y2Params.premises.${i}.rent`,x.rent)}</td><td>${nInput('',`y2Params.premises.${i}.transport`,x.transport)}</td></tr>`).join('');
 const machRows=p.machines.map((x,i)=>`<tr><td>${tInput('',`y2Params.machines.${i}.name`,x.name)}</td><td>${nInput('',`y2Params.machines.${i}.capacity`,x.capacity)}</td><td>${nInput('',`y2Params.machines.${i}.purchaseCost`,x.purchaseCost)}</td><td>${nInput('',`y2Params.machines.${i}.maintenance`,x.maintenance)}</td><td>${nInput('',`y2Params.machines.${i}.depreciation`,x.depreciation)}</td><td>${nInput('',`y2Params.machines.${i}.life`,x.life)}</td></tr>`).join('');
 $('#year2-settings').innerHTML=`${title('3. Year 2 Winter setup','Known Winter market forecast: 410,000 units — reference only, not promised sales.')}<div class="card"><div class="notice">Every value below is an editable estimate. Defaults copied from Year 1 are <strong>Year 1 reference only, not confirmed Year 2 rule.</strong></div><div class="fields">${nInput('Selling price (Sh/unit)','y2Params.price',p.price)}${nInput('Milk price (Sh/ton)','y2Params.milkPrice',p.milkPrice)}${nInput('Milk yield (units/ton)','y2Params.milkYield',p.milkYield)}${nInput('Fixed salaries','y2Params.salaries',p.salaries)}${nInput('Bonus rate (%)','y2Params.bonusRate',p.bonusRate)}${nInput('Tax rate (%)','y2Params.taxRate',p.taxRate)}</div><h3>Premises estimates</h3><table class="table"><thead><tr><th>Premise</th><th>Rent</th><th>Transport / sold unit</th></tr></thead><tbody>${premRows}</tbody></table><h3>Machine estimates</h3><table class="table"><thead><tr><th>Machine</th><th>Capacity</th><th>Purchase</th><th>Maintenance</th><th>Depreciation</th><th>Life</th></tr></thead><tbody>${machRows}</tbody></table></div>`;
}

function scenarioOpening(bridge) { if(state.autumnOverride.enabled) return { cash:round(state.autumnOverride.cash),debt:round(state.autumnOverride.debt),taxLoss:round(state.autumnOverride.taxLoss),machines:state.autumnOverride.m1Life>0?[{...state.y2Params.machines[0],id:'M1-actual',sourceId:'M1',remainingLife:round(state.autumnOverride.m1Life)}]:[]}; return bridge.ending; }
function pnl(r) { const rows=[['Revenue',r.revenue],['Milk',-r.milk],['Maintenance — all owned machines',-r.maintenance],['Depreciation — all owned machines',-r.depreciation],['Gross profit',r.grossProfit],['Transport',-r.transport],['Market spending',-r.market],['Bonus (positive gross profit)',-r.bonus],['Salaries',-r.salaries],['Rent',-r.rent],['Interest',-r.interest],['Other minimum costs',-r.minimumCosts],['Profit before tax',r.preTaxProfit],['Tax-loss pool used',-r.taxLossUsed],['Game tax',-r.tax],['Net profit',r.netProfit]];return `<table class="table"><tbody>${rows.map(([l,v])=>`<tr><td>${l}</td><td>${fmt(v)}</td></tr>`).join('')}</tbody></table>`;}
function scenarioCard(letter, s, r, sensitivity) {
 const p=state.y2Params, owned=(scenarioOpening(currentBridge).machines||[]), activeOptions=owned;
 const checks=(list,path,selected,label,empty='')=>`<div class="checks"><strong>${label}:</strong>${list.length?list.map(m=>`<label><input type="checkbox" data-array="${path}" value="${m.id}" ${selected?.includes(m.id)||selected?.includes(m.sourceId)||selected?.includes(m.modelId)?'checked':''}> ${m.name}</label>`).join(''):empty}</div>`;
 const premiseChecks=checks(p.premises,`scenario${letter}.premises`,s.premises,'Production premises');
 const machineChecks=checks(activeOptions,`scenario${letter}.machineUse`,s.machineUse,'Machine use','<em>No opening machines; purchase one before production.</em>');
 const buyChecks=checks(p.machines,`scenario${letter}.purchases`,s.purchases,'Machine purchases');
 const sensitivityText=sensitivity?`<div class="warning"><strong>Lower-sales sensitivity:</strong> At ${money(s.sensitivitySales)} sales, net profit would be ${fmt(sensitivity.netProfit)} and closing cash ${fmt(sensitivity.closingCash)}.</div>`:'';
 return `<article class="card scenario ${letter==='B'?'b':''}"><h3>Winter ${letter}</h3><div class="scenario-layout"><div><p class="subtle">Edit the plan; actual sales are limited by request, assumption, production, milk and capacity.</p><div class="fields">${nInput('Planned production',`scenario${letter}.production`,s.production)}${nInput('Milk purchased (tons)',`scenario${letter}.milkTons`,s.milkTons)}${nInput('Sales request',`scenario${letter}.salesRequest`,s.salesRequest)}${nInput('Assumed actual sales allocation',`scenario${letter}.assumedSales`,s.assumedSales)}${nInput('Market investment',`scenario${letter}.market`,s.market)}${nInput('Minimum costs',`scenario${letter}.minimumCosts`,s.minimumCosts)}${nInput('Borrowing',`scenario${letter}.borrowing`,s.borrowing)}${nInput('Interest rate (%)',`scenario${letter}.interestRate`,s.interestRate)}${nInput('Repayment term (seasons)',`scenario${letter}.repaymentTerm`,s.repaymentTerm)}${nInput('Principal repayment',`scenario${letter}.principalRepayment`,s.principalRepayment)}${nInput('Extra principal repayment',`scenario${letter}.extraRepayment`,s.extraRepayment)}${nInput('Lower-sales sensitivity',`scenario${letter}.sensitivitySales`,s.sensitivitySales)}</div>${premiseChecks}${machineChecks}${buyChecks}</div><div>${resultBlock(r)}${sensitivityText}<h4>Profit & loss</h4>${pnl(r)}<h4>Cash flow / position</h4><table class="table"><tbody><tr><td>Cash before finance</td><td>${fmt(r.cashBeforeFinance)}</td></tr><tr><td>Loan cash received</td><td>${fmt(r.borrowing)}</td></tr><tr><td>Principal repayments</td><td>${fmt(-r.principalRepayment)}</td></tr><tr><td>Machine purchases (cash, not P&L)</td><td>${fmt(-r.machinePurchases)}</td></tr><tr><td>Closing cash</td><td>${fmt(r.closingCash)}</td></tr><tr><td>Closing debt / tax-loss pool</td><td>${fmt(r.debt)} / ${fmt(r.taxLoss)}</td></tr></tbody></table><p class="subtle">Actual sales: ${money(r.actualSales)} · Spoilage: ${money(r.spoilage)} · Unused milk capacity: ${money(r.unusedMilk)} · Rent premises: ${r.premises.join(', ')||'none'}.</p></div></div></article>`;
}
let currentBridge;
function renderScenarios(bridge) {
 currentBridge=bridge; const opening=scenarioOpening(bridge); const calc=(s, sales=s.assumedSales)=>calculateSeason({...s, assumedSales:sales, opening, params:state.y2Params, machines:state.y2Params.machines}); const a=calc(state.scenarioA),b=calc(state.scenarioB),as=calc(state.scenarioA,state.scenarioA.sensitivitySales),bs=calc(state.scenarioB,state.scenarioB.sensitivitySales);
 $('#scenarios').innerHTML=`${title('4. Compare Winter A and Winter B','Both scenarios begin from the same Year 1 Autumn position. Transport is allocated across selected premises in proportion to their production share.')}<div class="card"><strong>Shared Year 2 opening position ${state.autumnOverride.enabled?'— manual actual-results override':'— calculated Year 1 bridge'}:</strong> cash ${fmt(opening.cash)}, debt ${fmt(opening.debt)}, unused tax losses ${fmt(opening.taxLoss)}, machines ${opening.machines.map(m=>`${m.name} (${m.remainingLife} seasons)`).join(', ')||'none'}.</div><div class="grid two">${scenarioCard('A',state.scenarioA,a,as)}${scenarioCard('B',state.scenarioB,b,bs)}</div>`;
 window.scenarioResults={a,b,as,bs};
}

function renderRecommendation() { const {a,b}=window.scenarioResults; const recommended=a.closingCash>=b.closingCash&&a.netProfit>=b.netProfit?'A':b.closingCash>=a.closingCash&&b.netProfit>=a.netProfit?'B':a.netProfit>b.netProfit?'A':'B'; const chosen=recommended==='A'?a:b, other=recommended==='A'?b:a; const differences=[`sales ${money(chosen.actualSales)} vs ${money(other.actualSales)}`,`spoilage ${money(chosen.spoilage)} vs ${money(other.spoilage)}`,`rent ${fmt(chosen.rent)} vs ${fmt(other.rent)}`,`machine costs ${fmt(chosen.maintenance+chosen.depreciation)} vs ${fmt(other.maintenance+other.depreciation)}`,`transport ${fmt(chosen.transport)} vs ${fmt(other.transport)}`,`market spending ${fmt(chosen.market)} vs ${fmt(other.market)}`,`interest ${fmt(chosen.interest)} vs ${fmt(other.interest)}`]; $('#recommendation').innerHTML=`${title('5. Results and recommendation','A calculation-based comparison, plus your editable classroom recommendation.')}<div class="grid two"><div class="card"><h3>Current calculation recommends Winter ${recommended}</h3><p>It has ${chosen.netProfit>=other.netProfit?'the stronger net profit':'a more cash-resilient position'} in the current inputs.</p><ul class="list">${differences.map(x=>`<li>${x}</li>`).join('')}</ul><p class="warning">Provisional: replace Year 1 Spring–Autumn estimates with real classroom results and confirm official Year 2 rules before deciding.</p></div><div class="card"><h3>Your recommendation record</h3><div class="fields">${select('Recommendation','recommendation.choice',state.recommendation.choice,[['A','Winter A'],['B','Winter B']])}${tInput('Main reason','recommendation.reason',state.recommendation.reason)}${tInput('Most important assumption','recommendation.assumption',state.recommendation.assumption)}</div><p class="subtle">Saved automatically in this browser.</p></div></div>`; }

function render() { const bridge=calculateBridge(state); renderWinterCheck(bridge); renderBridge(bridge); renderY2Settings(); renderScenarios(bridge); renderRecommendation(); bind(); }
function bind() { document.querySelectorAll('[data-path]').forEach(el=>el.addEventListener('change',()=>{ if(el.type==='checkbox') setPath(el.dataset.path,el.checked);else setPath(el.dataset.path,inputValue(el)); save();render();})); document.querySelectorAll('[data-array]').forEach(el=>el.addEventListener('change',()=>{const arr=getPath(el.dataset.array)||[];const next=el.checked?[...new Set([...arr,el.value])]:arr.filter(x=>x!==el.value);setPath(el.dataset.array,next);save();render();})); document.querySelectorAll('[data-season]').forEach(el=>el.addEventListener('click',()=>{state.uiSeason=el.dataset.season;save();render();})); document.querySelectorAll('[data-action="restore-winter"]').forEach(el=>el.addEventListener('click',()=>{state.winter={...clone(suppliedWinter),premises:['D']};save();render();})); }
render();
